# Generated by Django 4.2.7 on 2023-11-28 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pseudo_roulette', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='cell',
        ),
        migrations.AddField(
            model_name='cell',
            name='round',
            field=models.ManyToManyField(related_name='cells', to='pseudo_roulette.round'),
        ),
    ]
